# Golden Cheetah
## Use Python verions 2.7
Testing the GC Rest API

In [33]:
"""
Created on Wed Aug 31 11:55:18 2016
imports the latest activity files and plots power curves
@author: Gavin
"""

#from glob import glob
#path = "/users/gavin/Library/GoldenCheetah"
#athletes = [i.split('/')[-2] for i in glob(path+'/*/')]


import pandas as pd
import matplotlib.pylab as plt
plt.ion()

path = "http://localhost:12021/"


athletes = pd.read_csv(path)


for athlete in ['Gavin']: #athletes.name:
    zones = pd.read_csv(path+'/'+athlete+'/zones',skipinitialspace=True)
    
    
    history = pd.read_csv(path+'//'+athlete,skipinitialspace=True)
    history.index = history.date
    
    lastActivity = history.filename.iloc[-1]
    print(lastActivity)
    activity = pd.read_csv(path+'/'+athlete+'/activity/'+lastActivity+'?format=csv',skipinitialspace=True)
    #print(activity.head())    
    meanmax = pd.read_csv(path+'/'+athlete+'/meanmax/'+lastActivity,skipinitialspace=True)
    
    bests=pd.read_csv(path+'//'+athlete+'/meanmax/bests?since=2016/01/01',skipinitialspace=True)
    bests.plot('secs','watts',logx=True,title=athlete+': Power Curve')

2017_12_07_09_43_10.json

In [34]:
athletes

    name          dob  weight  height    sex
0  Gavin   1965/01/08      73   1.829   Male
1   temp   2000/01/01      75   0.000   Male

In [35]:
#activity

In [36]:
lastActivity

'2017_12_07_09_43_10.json'

In [37]:
zones

          date   cp     w'  pmax
0   1900/01/01  280  20000  1000
1   2015/10/01  317  24000  1097
2   2015/11/01  317  24000  1097
3   2015/11/10  326  20000  1700
4   2016/01/01  304  24000   982
5   2016/04/01  320  24000  1100
6   2016/07/08  329  24000  1100
7   2016/09/01  305  29000  1100
8   2017/01/04  270  22000  1000
9   2017/02/17  280  24000  1100
10  2017/03/27  290  24000  1100
11  2017/04/15  300  26000  1100
12  2017/05/04  305  28000  1100

In [38]:
meanmax

      secs    watts
0        1  752.000
1        2  748.500
2        3  747.000
3        4  737.250
4        5  734.800
5        6  720.667
6        7  705.143
7        8  677.875
8        9  641.556
9       10  608.300
10      11  573.000
11      12  539.167
12      13  511.385
13      14  487.357
14      15  466.200
15      16  446.625
16      17  429.765
17      18  415.056
18      19  402.737
19      20  391.000
20      21  380.381
21      22  376.864
22      23  376.217
23      24  375.625
24      25  373.800
25      26  373.077
26      27  372.259
27      28  370.357
28      29  366.931
29      30  363.433
...    ...      ...
3570  3571  210.559
3571  3572  210.559
3572  3573  210.559
3573  3574  210.559
3574  3575  210.559
3575  3576  210.559
3576  3577  210.559
3577  3578  210.559
3578  3579  210.559
3579  3580  210.559
3580  3581  209.500
3581  3582  209.500
3582  3583  209.500
3583  3584  209.500
3584  3585  209.500
3585  3586  209.500
3586  3587  209.500
3587  3588  209.500
3588  3589  209.500
3589  3590  209.500
3590  3591  209.500
3591  3592  209.500
3592  3593  209.500
3593  3594  209.500
3594  3595  209.500
3595  3596  209.500
3596  3597  209.500
3597  3598  209.500
3598  3599  209.500
3599  3600  209.500

[3600 rows x 2 columns]

In [39]:
history.iloc[-1:].T

date                                           2017/12/07
date                                           2017/12/07
time                                             09:43:10
filename                         2017_12_07_09_43_10.json
axPower                                           248.164
aPower_Relative_Intensity                         0.81365
aBikeScore                                        67.1406
Skiba_aVI                                         1.20018
aPower_Response_Index                             1.81527
aNP                                               250.139
aIF                                               0.82013
aTSS                                              68.2138
aVI                                               1.20973
aPower_Efficiency_Factor                          1.82972
aTSS_per_hour                                     67.2609
Aerobic_Decoupling                                21.2843
Activities                                              1
To_Exhaustion                                           0
Elapsed_Time                                            0
Duration                                             3651
Time_Moving                                          3606
Time_Carrying_(Est)                                     0
Elevation_Gain_Carrying_(Est)                           0
Distance                                          29.8703
Climb_Rating                                      0.00034
Athlete_Weight                                         73
Athlete_Bodyfat                                         0
Athlete_Bones                                           0
Athlete_Muscles                                         0
Athlete_Lean_Weight                                     0
Athlete_Bodyfat_Percent                                 0
...                                                   ...
W4_W'bal_Severe_Fatigue                                 0
W1_W'bal_Work_Low_Fatigue                         741.135
W2_W'bal_Work_Moderate_Fatigue                     15.618
W3_W'bal_Work_Heavy_Fatigue                             0
W4_W'bal_Work_Severe_Fatigue                            0
Below_CP_Work                                     738.993
Fraction_of_normal_RR_intervals                   93.7203
Average_of_all_NN_intervals                       427.601
Standard_deviation_of_NN                          71.1147
SDANN                                              120.36
SDNNIDX                                            18.879
rMSSD                                             6.54979
pNN5                                                    0
pNN10                                                   0
pNN15                                                   0
pNN20                                                   0
pNN25                                                   0
pNN30                                                   0
pNN35                                                   0
pNN40                                                   0
pNN45                                                   0
pNN50                                                   0
Rest_HR                                           116.045
Rest_AVNN                                         514.177
Rest_SDNN                                         66.5052
Rest_rMSSD                                        7.19123
Rest_PNN50                                              0
Rest_LF                                                 0
Rest_HF                                                 0
HRV_Recovery_Points                               4.95929

[347 rows x 1 columns]

In [63]:
history.shape
history.to_csv('History.csv')
history.describe().to_csv('Desc.csv')

In [67]:
mask = [c for c in history.columns if (history[c].max() != history[c].min())]
xx = history[mask]
xx.shape

(855, 245)

In [56]:
#'Zone' in 'H1_Percent_in_Zone'
#timeZoneMask = [c for c in xx.columns if 'Time_in_Zone' in c]
#xx[timeZoneMask].plot()

In [58]:
#pd.plotting.scatter_matrix(xx, alpha=0.2, figsize=(6, 6), diagonal='kde');

In [59]:
#from pandas.plotting import scatter_matrix

In [68]:
del(xx['Checksum'])
xx.to_csv('Gavin_History.csv')

In [47]:
xx[xx['Duration']==xx['Duration'].max()]

,date,time,filename,axPower,aPower_Relative_Intensity,aBikeScore,Skiba_aVI,aNP,aIF,aTSS,...,5_sec_Peak_WPK,10_sec_Peak_WPK,15_sec_Peak_WPK,20_sec_Peak_WPK,Watts_Per_Kilogram,Minimum_W'_bal,W'bal_TAU,W1_W'bal_Low_Fatigue,W1_W'bal_Work_Low_Fatigue,Below_CP_Work
date,,,,,,,,,,,,,,,,,,,,,
2014/04/13,2014/04/13,09:32:06,2014_04_13_07_32_06.json,209.747,0.7491,479.795,1.12843,218.251,0.77947,493.838,...,6.96164,6.53151,6.20548,6.10548,2.54624,7.81813,459,28621,4661.5,5275.28

In [19]:
xx.aPower_Response_Index.min()

0.0

In [71]:
history.columns[100:200]

Index([u'Efficiency_Factor', u'TSS_per_hour', u'Exhaustion_Best_R',
       u'Daniels_Points', u'Daniels_EqP', u'LNP', u'RTP', u'xPace', u'IWF',
       u'GOVSS', u'H1_Time_in_Zone', u'H2_Time_in_Zone', u'H3_Time_in_Zone',
       u'H4_Time_in_Zone', u'H5_Time_in_Zone', u'H6_Time_in_Zone',
       u'H7_Time_in_Zone', u'H8_Time_in_Zone', u'H9_Time_in_Zone',
       u'H10_Time_in_Zone', u'H1_Percent_in_Zone', u'H2_Percent_in_Zone',
       u'H3_Percent_in_Zone', u'H4_Percent_in_Zone', u'H5_Percent_in_Zone',
       u'H6_Percent_in_Zone', u'H7_Percent_in_Zone', u'H8_Percent_in_Zone',
       u'H9_Percent_in_Zone', u'H10_Percent_in_Zone', u'Left/Right_Balance',
       u'P1_Time_in_Pace_Zone', u'P2_Time_in_Pace_Zone',
       u'P3_Time_in_Pace_Zone', u'P4_Time_in_Pace_Zone',
       u'P5_Time_in_Pace_Zone', u'P6_Time_in_Pace_Zone',
       u'P7_Time_in_Pace_Zone', u'P8_Time_in_Pace_Zone',
       u'P9_Time_in_Pace_Zone', u'P10_Time_in_Pace_Zone',
       u'P1_Percent_in_Pace_Zone', u'P2_Percent_in_Pace_Zone',
       u'P3_Percent_in_Pace_Zone', u'P4_Percent_in_Pace_Zone',
       u'P5_Percent_in_Pace_Zone', u'P6_Percent_in_Pace_Zone',
       u'P7_Percent_in_Pace_Zone', u'P8_Percent_in_Pace_Zone',
       u'P9_Percent_in_Pace_Zone', u'P10_Percent_in_Pace_Zone',
       u'10_sec_Peak_Pace', u'15_sec_Peak_Pace', u'20_sec_Peak_Pace',
       u'30_sec_Peak_Pace', u'1_min_Peak_Pace', u'2_min_Peak_Pace',
       u'3_min_Peak_Pace', u'5_min_Peak_Pace', u'8_min_Peak_Pace',
       u'10_min_Peak_Pace', u'20_min_Peak_Pace', u'30_min_Peak_Pace',
       u'60_min_Peak_Pace', u'90_min_Peak_Pace', u'10_sec_Peak_Pace_Swim',
       u'15_sec_Peak_Pace_Swim', u'20_sec_Peak_Pace_Swim',
       u'30_sec_Peak_Pace_Swim', u'1_min_Peak_Pace_Swim',
       u'2_min_Peak_Pace_Swim', u'3_min_Peak_Pace_Swim',
       u'5_min_Peak_Pace_Swim', u'8_min_Peak_Pace_Swim',
       u'10_min_Peak_Pace_Swim', u'20_min_Peak_Pace_Swim',
       u'30_min_Peak_Pace_Swim', u'60_min_Peak_Pace_Swim',
       u'90_min_Peak_Pace_Swim', u'Best_50m', u'Best_100m', u'Best_200m',
       u'Best_400m', u'Best_500m', u'Best_800m', u'Best_1000m', u'Best_1500m',
       u'Best_2000m', u'Best_3000m', u'Best_4000m', u'Best_5000m',
       u'Best_10km', u'Best_15km', u'Best_20km', u'Best_Half_Marathon',
       u'Best_30km', u'Best_40km', u'Best_Marathon', u'1_min_Peak_Pace_HR',
       u'5_min_Peak_Pace_HR'],
      dtype='object')

In [72]:
activity.columns

Index([u'secs', u'cad', u'hr', u'km', u'kph', u'nm', u'watts', u'alt', u'lon',
       u'lat', u'headwind', u'slope', u'temp', u'interval', u'lrbalance',
       u'lte', u'rte', u'lps', u'rps', u'smo2', u'thb', u'o2hb', u'hhb'],
      dtype='object')